### ISSUE TITLE
When running ./build.sh I get an error

### ISSUE THREAD

**Issue by mAiNiNfEcTiOn** [Travix-International/appix#46]
# What's the issue:

I did some changes and wanted to build the project on my computer to test it.
Followed the documentation so everything was fine, including the env variables were set (just with empty strings for now).

When I executed `./build.sh` I get this error:

```bash
Building Mac binary...
cmd/appix/main.go:12:2: cannot find package "github.com/Travix-International/appix" in any of:
        /Users/RMachado/golang/src/Travix-International/appix/vendor/github.com/Travix-International/appix (vendor tree)
        /usr/local/Cellar/go/1.6.2/libexec/src/github.com/Travix-International/appix (from $GOROOT)
        /Users/RMachado/golang/src/github.com/Travix-International/appix (from $GOPATH)
cmd/appix/main.go:13:2: cannot find package "github.com/Travix-International/appix/config" in any of:
        /Users/RMachado/golang/src/Travix-International/appix/vendor/github.com/Travix-International/appix/config (vendor tree)
        /usr/local/Cellar/go/1.6.2/libexec/src/github.com/Travix-International/appix/config (from $GOROOT)
        /Users/RMachado/golang/src/github.com/Travix-International/appix/config (from $GOPATH)
```

Also, in case you're wondering, here's the values of the variables `$GOPATH` and `$GOROOT`:

```bash
➜  appix git:(proposal-ignore-strings-contains) ✗ echo $GOPATH
/Users/RMachado/golang
➜  appix git:(proposal-ignore-strings-contains) ✗ echo $GOROOT

```

Also, I had to comment the other OS'es builds 'cause it was triggering errors as well.

**Comment by fahad19** [comment]
where are you trying to build it from? `$ pwd`?

**Comment by mAiNiNfEcTiOn** [comment]
Trying to build from `/Users/RMachado/golang/src/Travix-International/appix/src/github.com/Travix-International/appix`

**Comment by fahad19** [comment]
I just cloned the repo, latest master, and successfully build it.

The repository itself should be cloned in `$GOPATH/src/Travix-International/appix`.

For example, my $GOPATH is `~/go`, so I cloned the repo in `~/go/src/github.com/Travix-International/appix`.

```
fahad at fahad-mbpr in ~/go/src/github.com/Travix-International/appix on master [!]
$ ./build.sh
Building Mac binary...
Done!
```

The `build.sh` file was modified to only build for `darwin`.

**Comment by mAiNiNfEcTiOn** [comment]
Yeah got it running as well...

Docs are wrong... should be cloned on `$GOPATH/src/github.com/Travix-International/appix` and not `$GOPATH/src/Travix-International/appix`.

Will issue PR to fix them.

**Comment by fahad19** [comment]
I updated my previous comment to contain the correct path, it should include `github.com` in the path.

**Comment by mAiNiNfEcTiOn** [comment]
@fahad19 I know, but the docs told me to do the clone on `src/Travix-International` instead of the correct one ->  `src/github.com/Travix-International/...`

**Comment by fahad19** [comment]
@mAiNiNfEcTiOn: yep, just noticed the README has wrong clone path. apologies for the mistake. your PR would be very welcome :D
