### ISSUE TITLE
v1.1.7 breaks AppCatalog push (assuming via watch)

### ISSUE THREAD

**Issue by mAiNiNfEcTiOn** [Travix-International/appix#50]
# Problem

Updating to v1.1.7 causes the following problem:

![pasted image at 2017_02_07 10_28 am](https://cloud.githubusercontent.com/assets/1002056/22682701/851a9b44-ed14-11e6-9b17-3e44cc1301ae.png)

(Picture from Aliaksandr Kavalenka)

Rolling back to v1.1.6 seems to solve the issue for now.

**Comment by mAiNiNfEcTiOn** [comment]
It might be related with some downtime on the AppCatalog :-/

**Comment by alexmiranda** [comment]
The app catalog integration tests are passing in my local, but failing in the pipeline. I will get it fixed soon. For now, I will mark release 1.1.7 as pre-release, so no one gets it before the catalog changes are live. Thanks Ricardo!

**Comment by mAiNiNfEcTiOn** [comment]
@alexmiranda the Catalog is down, so I'm taking a look at it ;)

**Comment by alexmiranda** [comment]
Ok, the problem has nothing to do with the current state of the integration tests pipeline. It's only because it's down. Pushing to app catalog is being retried multiple times as expected, so there is nothing wrong with appix push. I will check appix watch.

**Comment by markvincze** [comment]
I think this was caused not by `appix` itself, but the AppCatalog being down. @mAiNiNfEcTiOn, can you verify?

**Comment by mAiNiNfEcTiOn** [comment]
@markvincze I am afraid not, here's the proof:

![screen shot 2017-02-07 at 13 03 48](https://cloud.githubusercontent.com/assets/1002056/22690428/147dad1e-ed36-11e6-973d-ff371bd437b5.png)

**Comment by markvincze** [comment]
@mAiNiNfEcTiOn investigated more and found out that the error happens if we don't have the `auth.json` file present in `~/.appix`.
@alexmiranda can you take a look if you see what could cause this in 1.1.7?

**Comment by alexmiranda** [comment]
Yep, looking into that @markvincze

**Comment by alexmiranda** [comment]
@mAiNiNfEcTiOn @markvincze I have issued a PR to fix this
https://github.com/Travix-International/appix/pull/51

**Comment by didinight239** [comment]
How is it to work for Travix and continue stealing Jean?

**Comment by didinight239** [comment]
How is it to work for Travix and continue stealing Jean?
